export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const OPEN_LOGIN_REGISTRATION_MODAL = "OPEN_LOGIN_REGISTRATION_MODAL";
export const CLOSE_LOGIN_REGISTRATION_MODAL = "CLOSE_LOGIN_REGISTRATION_MODAL";

export default {
  LOGIN,
  LOGOUT,
  REGISTER,
  OPEN_LOGIN_REGISTRATION_MODAL,
  CLOSE_LOGIN_REGISTRATION_MODAL,
};
