export const SAVE_LOGIN = "SAVE_LOGIN";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const REGISTER = "REGISTER";
export const OPEN_LOGIN_REGISTRATION_MODAL = "OPEN_LOGIN_REGISTRATION_MODAL";
export const CLOSE_LOGIN_REGISTRATION_MODAL = "CLOSE_LOGIN_REGISTRATION_MODAL";

export default {
  SAVE_LOGIN,
  SAVE_USER_DATA,
  CLEAR_USER_DATA,
  REGISTER,
  OPEN_LOGIN_REGISTRATION_MODAL,
  CLOSE_LOGIN_REGISTRATION_MODAL,
};
